In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

READING NUMPY EXAMPLE CODE

In [2]:
a = np.array([[1,2,3],[4,5,6]])
print("\n The two-d array is:\n",a)


 The two-d array is:
 [[1 2 3]
 [4 5 6]]


ARRAY INITIALIZATION USING A PYTHON LIST

In [5]:
a = np.array([1,2,3,4,5,6])
print("\n The Output is:\n a =",a)


 The Output is:
 a = [1 2 3 4 5 6]


In [7]:
## ACCESSING THE ELEMENT IN THE ARRAY
a[[0,4,2]]

array([1, 5, 3])

In [8]:
### The Array is also mutable
a[0] = 10
print("The new array is:\n",a)

The new array is:
 [10  2  3  4  5  6]


In [9]:
### Slicing the list
a[:3]

array([10,  2,  3])

VIEW, ORIGINAL ARRAY AND MUTING

In [12]:
### Muting the original array using the sliced view
b = a[3:]
print("The view is:\n",b)
b[2] = 20
print("The original array is:\n",a)

The view is:
 [4 5 6]
The original array is:
 [10  2  3  4  5 20]


TWO OR HIGHER DIMENSIONAL ARRAYS

In [13]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("The array is:\n",a)

The array is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


MULTIDIMENSIONAL ARRAYS

In [15]:
### Two Dimensional array
# Refers to an array of arrays
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
print("This is a 2D array:\n",a)

This is a 2D array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [16]:
### Three Dimensional array
# Refers to an array of 2D arrays
a = np.array([
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]
    ]
])
print("This is a 3D array:\n",a)

This is a 3D array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
